-- Document key operational tables with Postgres comments.
-- These comments power data cataloging and make `\d+` output self-explanatory.

COMMENT ON TABLE public.classes IS
  'Catalog of every class or session offered by providers, including scheduling, pricing, and SEO metadata used by personalization and search.';

COMMENT ON TABLE public.providers IS
  'Profiles for organisations delivering classes, storing onboarding state, contact information, and marketplace participation flags.';

COMMENT ON TABLE public.provider_growth_score IS
  'Weekly growth score snapshots per provider, including computed metrics, recommendations, and trend data powering the growth dashboard.';

COMMENT ON TABLE public.analytics_events IS
  'Raw analytics events captured from product interactions (searches, views, conversions) used to compute provider and member insights.';

COMMENT ON TABLE public.provider_analytics_weekly IS
  'Aggregated weekly analytics per provider (views, bookings, conversion rate) that back admin/provider dashboards.';

COMMENT ON TABLE public.provider_referral_analytics IS
  'Referral funnel analytics tied to providers, tracking clicks, registrations, and bookings generated by referral programs.';

